import { theme } from 'antd'
import { colors as c } from './tokens'

export const darkTheme = {
  algorithm: theme.darkAlgorithm,
  token: {
    colorPrimary: c.primary, colorSuccess: c.success, colorWarning: c.warning, colorError: c.error, colorInfo: c.info,
    colorBgLayout: c.body, colorBgContainer: c.surface, colorBgElevated: c.elevated, colorBorder: c.border,
    colorBorderSecondary: '#143d77', colorText: c.text, colorTextHeading: c.text, colorTextSecondary: c.secondary,
    colorTextTertiary: c.muted, colorTextDisabled: 'rgba(255,255,255,.26)', colorFillAlter: c.header,
    colorBgContainerDisabled: '#113577', borderRadius: 4, borderRadiusLG: 4, borderRadiusSM: 4,
    fontFamily: '-apple-system, BlinkMacSystemFont, "PingFang SC", "Microsoft YaHei", sans-serif',
    fontSize: 14, controlHeight: 32, controlHeightSM: 24, controlHeightLG: 40,
    boxShadow: '0 4px 16px rgba(0,0,0,.24)',
  },
  components: {
    Button: {
      primaryShadow: 'none', defaultShadow: 'none', dangerShadow: 'none', primaryColor: '#fff',
      controlHeight: 32, controlHeightSM: 32, controlHeightLG: 40,
      contentFontSize: 12, contentFontSizeSM: 12, contentFontSizeLG: 14,
      paddingInline: 16, paddingInlineSM: 16, paddingInlineLG: 20, iconGap: 6,
      defaultBg: 'transparent', defaultColor: c.secondary, defaultBorderColor: 'rgba(255,255,255,.4)',
      defaultHoverBg: 'transparent', defaultHoverColor: c.secondary, defaultHoverBorderColor: 'rgba(255,255,255,.6)',
      defaultActiveBg: '#76bbff', defaultActiveColor: c.secondary, defaultActiveBorderColor: c.primary,
      colorPrimary: c.primary, colorPrimaryHover: '#1778de', colorPrimaryActive: '#3c9eff',
      colorLink: c.primary, colorLinkHover: 'rgba(26,141,255,.8)', colorLinkActive: '#3c9dff',
      colorBgContainerDisabled: 'transparent', colorTextDisabled: c.muted, borderColorDisabled: 'rgba(255,255,255,.26)',
    },
    Menu: { itemHeight: 40, itemMarginInline: 0, itemMarginBlock: 0, itemBorderRadius: 0, subMenuItemBorderRadius: 0,
      darkItemBg: 'transparent', darkSubMenuItemBg: 'transparent', darkItemColor: c.secondary,
      darkItemSelectedBg: 'rgba(26,141,255,.2)', darkItemSelectedColor: c.primary,
      darkItemHoverBg: 'rgba(26,141,255,.12)', darkItemHoverColor: c.text },
    Table: { headerBg: c.header, headerColor: c.text, rowHoverBg: c.hover, borderColor: '#143d77',
      cellPaddingBlock: 8, cellPaddingInline: 16, cellFontSize: 14,
      cellPaddingBlockMD: 8, cellPaddingInlineMD: 16, cellFontSizeMD: 14,
      cellPaddingBlockSM: 8, cellPaddingInlineSM: 16, cellFontSizeSM: 14,
      headerBorderRadius: 4, headerSplitColor: 'transparent', rowSelectedBg: '#123e77', rowSelectedHoverBg: c.hover },
    Card: { headerHeight: 48, headerHeightSM: 40, headerFontSize: 14, bodyPadding: 24, bodyPaddingSM: 16 },
    Modal: { contentBg: c.surface, headerBg: c.surface, titleFontSize: 16 },
    Drawer: { colorBgElevated: c.surface },
    Alert: {
      colorInfo: c.primary, colorInfoBg: 'rgba(26,141,255,.06)', colorInfoBorder: 'rgba(26,141,255,.16)',
    },
    Input: { activeShadow: '0 0 0 2px rgba(26,141,255,.15)' },
    Select: {
      controlHeight: 32, controlHeightSM: 32, fontSize: 14, fontSizeIcon: 12,
      paddingSM: 9, controlPaddingHorizontalSM: 9, showArrowPaddingInlineEnd: 24,
      selectorBg: c.surface, colorBgBase: c.surface, clearBg: c.surface, colorBorder: c.border,
      colorText: c.text, colorTextPlaceholder: c.secondary, colorTextQuaternary: c.text,
      colorIcon: c.secondary, colorIconHover: c.primary, colorTextDisabled: 'rgba(255,255,255,.26)',
      hoverBorderColor: c.primary, activeBorderColor: c.primary, activeOutlineColor: 'rgba(26,141,255,.15)',
      colorBgElevated: c.elevated, boxShadowSecondary: '0 4px 16px rgba(0,0,0,.3)',
      optionHeight: 32, optionFontSize: 12, optionLineHeight: '20px', optionPadding: '6px 8px',
      optionSelectedFontWeight: 400, optionSelectedColor: c.primary,
      optionSelectedBg: c.hover, optionActiveBg: c.hover,
      multipleItemHeight: 24, multipleItemHeightSM: 24, multipleItemBg: '#1c3f81',
      multipleItemBorderColor: 'transparent', multipleSelectorBgDisabled: '#113577',
    },
    Tabs: { titleFontSize: 14, titleFontSizeSM: 14, horizontalItemGutter: 32,
      horizontalItemPadding: '10px 0', horizontalItemPaddingSM: '10px 0', horizontalMargin: '0 0 16px',
      itemColor: c.secondary, itemSelectedColor: c.primary, itemHoverColor: c.primary, inkBarColor: c.primary,
      cardBg: 'transparent', cardHeight: 40, cardPadding: '8px 16px', cardPaddingSM: '8px 16px' },
    Pagination: { itemSize: 32, itemSizeSM: 32, itemBg: 'transparent', itemActiveBg: c.primary,
      colorPrimary: '#fff', colorPrimaryHover: '#fff', colorText: c.secondary, colorBgContainer: 'transparent' },
    Radio: { controlHeight: 32, controlHeightSM: 32, fontSize: 12, buttonPaddingInline: 16,
      buttonBg: '#1c4694', buttonColor: c.secondary, buttonCheckedBg: c.primary,
      buttonSolidCheckedBg: c.primary, buttonSolidCheckedColor: '#fff',
      buttonSolidCheckedHoverBg: '#1778de', buttonSolidCheckedActiveBg: '#3c9eff',
      buttonCheckedBgDisabled: '#1259ac', buttonCheckedColorDisabled: c.muted,
      colorBgContainerDisabled: '#113577', colorTextDisabled: c.muted },
    Tag: { defaultBg: c.header, defaultColor: c.secondary },
  },
}

export const printTheme = {
  algorithm: theme.defaultAlgorithm,
  token: { colorBgContainer: '#fff', colorText: '#172033', colorTextHeading: '#0f172a', colorTextSecondary: '#64748b', colorBorder: '#dbe5f1', borderRadius: 4 },
  components: { Table: { headerBg: '#f1f5f9', headerColor: '#172033', rowHoverBg: '#f8fafc' }, Card: { colorBgContainer: '#fff' } },
}
